### ISSUE TITLE
How to use on Windows?

### ISSUE THREAD

**Issue by kazuser** [lmbelo/python3-embeddable#3]
Hi!

Could you please explain step-by-step how to use it? I want to build 3.10.11 (Windows) but can't figure it out :(

**Comment by lmbelo** [comment]
It uses a GH Action to build embeddable. Have a look [here](https://github.com/lmbelo/python3-embeddable/blob/main/.github/workflows/build_windows.yml).
It basically set the arch and pyver env variables and call the batch script.
